com.germandebustamante.fuelio.feature.list.state.GasStationItemVO
com.germandebustamante.fuelio.feature.list.state.GasStationsUIState
com.germandebustamante.fuelio.feature.list.state.ContentState.Success
com.germandebustamante.fuelio.feature.detail.state.GasStationDetailUIState
com.germandebustamante.fuelio.feature.settings.state.SettingsUIState
com.germandebustamante.fuelio.feature.app.state.AppUIState
