package com.germandebustamante.fuelio.core.fake

import com.germandebustamante.fuelio.core.domain.gasstation.model.GasStationBO
import com.germandebustamante.fuelio.core.domain.gasstation.model.ScheduleSegmentBO
import kotlinx.datetime.DayOfWeek

private val alwaysOpen = listOf(ScheduleSegmentBO(DayOfWeek.MONDAY, DayOfWeek.SUNDAY, null, null))

val fakeGasStations = listOf(
    GasStationBO(
        id = "7153",
        name = "REPSOL",
        address = "AVDA DE ANDALUCIA S/N",
        city = "AGUADULCE",
        municipality = "Aguadulce",
        province = "SEVILLA",
        zipCode = "41550",
        latitude = 37.249611,
        longitude = -5.005250,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.535,
        gasolinePrice98 = null,
        dieselPrice = 1.829,
        dieselPremiumPrice = 1.929,
    ),
    GasStationBO(
        id = "10608",
        name = "MOEVE",
        address = "AUTOVIA A-92 KM. 97",
        city = "AGUADULCE",
        municipality = "Aguadulce",
        province = "SEVILLA",
        zipCode = "41550",
        latitude = 37.263528,
        longitude = -4.959194,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.571,
        gasolinePrice98 = null,
        dieselPrice = 1.862,
        dieselPremiumPrice = 1.912,
    ),
    GasStationBO(
        id = "7096",
        name = "CEPSA",
        address = "CARRETERA N-IV KM. 162,8",
        city = "ALCALA DE GUADAIRA",
        municipality = "Alcalá de Guadaíra",
        province = "SEVILLA",
        zipCode = "41500",
        latitude = 37.215500,
        longitude = -5.919278,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.699,
        gasolinePrice98 = null,
        dieselPrice = 1.829,
        dieselPremiumPrice = 1.889,
    ),
    GasStationBO(
        id = "7095",
        name = "REPSOL",
        address = "CARRETERA A-8028 KM. 3",
        city = "ALCALA DE GUADAIRA",
        municipality = "Alcalá de Guadaíra",
        province = "SEVILLA",
        zipCode = "41500",
        latitude = 37.375694,
        longitude = -5.908694,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.599,
        gasolinePrice98 = null,
        dieselPrice = 1.849,
        dieselPremiumPrice = 1.899,
    ),
    GasStationBO(
        id = "11244",
        name = "NOVAOIL",
        address = "AUTOPISTA A-92 KM. 7,700",
        city = "ALCALA DE GUADAIRA",
        municipality = "Alcalá de Guadaíra",
        province = "SEVILLA",
        zipCode = "41500",
        latitude = 37.357361,
        longitude = -5.867000,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.522,
        gasolinePrice98 = null,
        dieselPrice = 1.711,
        dieselPremiumPrice = 1.722,
    ),
    GasStationBO(
        id = "7045",
        name = "ECONOIL",
        address = "POLIGONO INDUSTRIAL CERRO CABEZA HERMOSA, AUTOVIA A-92 KM 7,8",
        city = "ALCALA DE GUADAIRA",
        municipality = "Alcalá de Guadaíra",
        province = "SEVILLA",
        zipCode = "41500",
        latitude = 37.352917,
        longitude = -5.858556,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.549,
        gasolinePrice98 = null,
        dieselPrice = 1.699,
        dieselPremiumPrice = null,
    ),
    GasStationBO(
        id = "12130",
        name = "S.C.A. NTRA. SRA. DE LA FUENSANTA",
        address = "CALLE EXTRAMUROS, S/N",
        city = "BADOLATOSA",
        municipality = "Badolatosa",
        province = "SEVILLA",
        zipCode = "41570",
        latitude = 37.272111,
        longitude = -4.694361,
        schedule = alwaysOpen,
        gasolinePrice95 = null,
        gasolinePrice98 = null,
        dieselPrice = 2.074,
        dieselPremiumPrice = null,
    ),
    GasStationBO(
        id = "12632",
        name = "LAVABU",
        address = "AVENIDA JESUS NAZARENO, 99",
        city = "CABEZAS DE SAN JUAN (LAS)",
        municipality = "Cabezas de San Juan (Las)",
        province = "SEVILLA",
        zipCode = "41730",
        latitude = 36.992250,
        longitude = -5.940250,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.678,
        gasolinePrice98 = null,
        dieselPrice = 1.779,
        dieselPremiumPrice = null,
    ),
    GasStationBO(
        id = "10159",
        name = "SAN TEODOMIRO",
        address = "CARRETERA SE-122 KM. 0,65",
        city = "CARMONA",
        municipality = "Carmona",
        province = "SEVILLA",
        zipCode = "41410",
        latitude = 37.482583,
        longitude = -5.644111,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.529,
        gasolinePrice98 = null,
        dieselPrice = 1.745,
        dieselPremiumPrice = null,
    ),
    GasStationBO(
        id = "10897",
        name = "BP",
        address = "CARRETERA SEVILLA MALAGA KM. 4",
        city = "ALCALA DE GUADAIRA",
        municipality = "Alcalá de Guadaíra",
        province = "SEVILLA",
        zipCode = "41500",
        latitude = 37.376417,
        longitude = -5.890278,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.595,
        gasolinePrice98 = 1.735,
        dieselPrice = 1.879,
        dieselPremiumPrice = 1.969,
    ),
    GasStationBO(
        id = "12972",
        name = "OCTANOS",
        address = "ROTONDA ADOLFO SUAREZ, 54",
        city = "DOS HERMANAS",
        municipality = "Dos Hermanas",
        province = "SEVILLA",
        zipCode = "41700",
        latitude = 37.298500,
        longitude = -5.925028,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.669,
        gasolinePrice98 = 1.729,
        dieselPrice = 1.779,
        dieselPremiumPrice = 1.789,
    ),
    GasStationBO(
        id = "16317",
        name = "BALLENOIL",
        address = "CALLE VIRGEN DEL CARMEN, S/N",
        city = "FUENTES DE ANDALUCIA",
        municipality = "Fuentes de Andalucía",
        province = "SEVILLA",
        zipCode = "41420",
        latitude = 37.464944,
        longitude = -5.343472,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.489,
        gasolinePrice98 = null,
        dieselPrice = 1.679,
        dieselPremiumPrice = 1.689,
    ),
    GasStationBO(
        id = "10330",
        name = "MAIRENA AGRICOLA, S.C.A.",
        address = "CALLE CAMINO DE ALCONCHEL, 42",
        city = "MAIRENA DEL ALCOR",
        municipality = "Mairena del Alcor",
        province = "SEVILLA",
        zipCode = "41510",
        latitude = 37.375889,
        longitude = -5.740778,
        schedule = alwaysOpen,
        gasolinePrice95 = null,
        gasolinePrice98 = null,
        dieselPrice = 1.691,
        dieselPremiumPrice = null,
    ),
    GasStationBO(
        id = "6433",
        name = "SHELL",
        address = "AVDA. PARQUE NORTE S/N",
        city = "PALACIOS Y VILLAFRANCA",
        municipality = "Palacios y Villafranca (Los)",
        province = "SEVILLA",
        zipCode = "41720",
        latitude = 37.168444,
        longitude = -5.928611,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.549,
        gasolinePrice98 = 1.689,
        dieselPrice = 1.819,
        dieselPremiumPrice = 1.899,
    ),
    GasStationBO(
        id = "7471",
        name = "GALP",
        address = "AVENIDA ANDALUCIA, 44",
        city = "SEVILLA",
        municipality = "Sevilla",
        province = "SEVILLA",
        zipCode = "41006",
        latitude = 37.386472,
        longitude = -5.947333,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.509,
        gasolinePrice98 = 1.649,
        dieselPrice = 1.704,
        dieselPremiumPrice = 1.704,
    ),
    GasStationBO(
        id = "7301",
        name = "CEPSA",
        address = "AVENIDA CONSTITUCION, 68",
        city = "VILLANUEVA RIO Y MINAS",
        municipality = "Villanueva del Río y Minas",
        province = "SEVILLA",
        zipCode = "41350",
        latitude = 37.651028,
        longitude = -5.721667,
        schedule = alwaysOpen,
        gasolinePrice95 = 1.739,
        gasolinePrice98 = null,
        dieselPrice = 1.849,
        dieselPremiumPrice = null,
    ),
)
